name: ci-cd
on:
  push:
    branches: [ main ]
jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r app/requirements.txt pytest mypy ruff black
      - run: ruff check . && black --check . && mypy --explicit-package-bases .
      - run: pytest -q --maxfail=1 --disable-warnings
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/EL-Bied-Ali/devops-fastapi-pipeline:latest
            ghcr.io/EL-Bied-Ali/devops-fastapi-pipeline:${{ github.sha }}
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" -p "${{ secrets.GHCR_TOKEN }}"
            sed -i 's#ghcr.io/.*/.*:.*#ghcr.io/EL-Bied-Ali/devops-fastapi-pipeline:latest#g' ~/app/compose.yml
            docker compose -f ~/app/compose.yml pull
            docker compose -f ~/app/compose.yml up -d
