name: ci-cd
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r app/requirements.txt pytest mypy ruff black httpx
      - name: Lint & type-check
        run: ruff check . && black --check . && mypy --explicit-package-bases .
      - name: Pytest
        run: pytest -q --maxfail=1 --disable-warnings
        env: { PYTHONPATH: ${{ github.workspace }} }
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR (GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/el-bied-ali/devops-fastapi-pipeline:latest
            ghcr.io/el-bied-ali/devops-fastapi-pipeline:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
